services:
  db:
    image: postgres:16
    container_name: news_db
    restart: always
    environment:
      POSTGRES_DB: news
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: ["5435:5432"]
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: ./api
    container_name: news_api
    restart: always
    env_file:
      - ./api/.env
    depends_on:
      - db
    ports: ["3001:3001"]

volumes:
  db_data:



